#!/bin/bash
# LightDock run script for 3GT8_raw
# Generated by egfr_pipeline.phase1.lightdock_validation
#
# Prerequisites:
#   pip install lightdock3
#   or: conda install -c bioconda lightdock
#
# Usage:
#   cd output/phase1_ppi/3GT8_raw/lightdock
#   bash run_lightdock_3GT8_raw.sh

set -e

INPUT_PDB="/home/user/codex_ligand/input/PPI/phase1/docking_3GT8_raw_ext_beta_meander.pdb"
WORKDIR="output/phase1_ppi/3GT8_raw/lightdock"
cd "$WORKDIR"

echo "=== LightDock Secondary Validation: 3GT8_raw ==="
echo "Input: $INPUT_PDB"
echo "Scoring: fastdfire"
echo "Swarms: 400, Glowworms: 200, Steps: 100"

# Step 1: Split PDB into receptor (chain A) and partner (chain B)
echo "Splitting input PDB..."
python3 -c "
with open('$INPUT_PDB') as f:
    lines = f.readlines()
with open('receptor.pdb', 'w') as r, open('partner.pdb', 'w') as p:
    for line in lines:
        if line.startswith(('ATOM', 'HETATM')):
            chain = line[21]
            if chain == 'A':
                r.write(line)
            elif chain == 'B':
                p.write(line)
    r.write('END\n')
    p.write('END\n')
"

# Step 2: LightDock setup
echo "Running lightdock3_setup..."
lightdock3_setup.py receptor.pdb partner.pdb \
    -s 400 \
    -g 200 \
    --noxt --noh

# Step 3: LightDock run
echo "Running lightdock3..."
lightdock3.py setup.json 100 \
    -s fastdfire \
    -c 2

# Step 4: Generate top poses
echo "Generating top poses..."
lgd_generate_conformations.py receptor.pdb partner.pdb \
    --top 10

# Step 5: Rank and cluster
echo "Ranking results..."
lgd_cluster_bsas.py setup.json

echo "=== LightDock complete for 3GT8_raw ==="
echo "Run extraction next:"
echo "  python -m egfr_pipeline.phase1.lightdock_validation --extract --state 3GT8_raw"
