bootstrap:
  n_replicates: 10
  sample_fraction: 0.8
  seed: 42
exhaustiveness: 8
experimental: null
ligands:
- id: '173940'
  pdbqt: input/ligands/173940_ligand.pdbqt
  sdf: input/ligands/173940_ligand.sdf
- id: '97806'
  pdbqt: input/ligands/97806_ligand.pdbqt
  sdf: input/ligands/97806_ligand.sdf
- id: VAX-C12_0
  pdbqt: input/ligands/VAX-C12_0_ligand.pdbqt
  sdf: input/ligands/VAX-C12_0_ligand.sdf
max_workers: 16
mode: blind
n_poses: 5
output_root: ./output
postprocess:
  cluster_pockets: false
  compare_pockets: false
  comparison_centroid_cutoff: 15.0
  contact_cutoff: 4.0
  extract_contacts: false
  extract_ppi_residues: false
  generate_report: false
  keep_chain: false
  merge_by_residue: false
  merge_jaccard: 0.3
  merge_overlap: 0.5
  parse_results: false
  pocket_cutoff: 4.0
  summarize_pockets: false
ppi:
  afm_models: null
  afm_settings:
    contact_cutoff: 8.0
    partner_chain: B
    receptor_chain: A
  pyrosetta_result_dirs: null
project_name: full_test
receptors:
- chain: A
  id: 3GT8_raw
  pdb: input/receptors/3GT8_raw.pdb
  pdbqt: input/receptors/3GT8_raw_receptor.pdbqt
  source_type: raw_3GT8
- chain: A
  id: 3GT8_cl38_48
  pdb: input/receptors/3GT8_cl38_48.pdb
  pdbqt: input/receptors/3GT8_cl38_48_receptor.pdbqt
  source_type: md_cluster_38_48
- chain: A
  id: 3GT8_cl85_100
  pdb: input/receptors/3GT8_cl85_100.pdb
  pdbqt: input/receptors/3GT8_cl85_100_receptor.pdbqt
  source_type: md_cluster_85_100
vina:
  exhaustiveness: 8
  min_box: 70.0
  mode: blind
  n_poses: 5
  padding: 5.0
