#!/bin/bash
# Phase 2 TG 2.1: Pocket Proposal Execution Script
# Generated by egfr_pipeline.phase2.pocket_proposal
#
# Run this script on the production server where fpocket and/or P2Rank
# are installed. Both tools are optional — the parser handles missing output.
#
# Usage:
#   bash pocket_proposal_run.sh
#   bash pocket_proposal_run.sh fpocket    # fpocket only
#   bash pocket_proposal_run.sh p2rank     # P2Rank only

set -euo pipefail

OUTPUT_BASE="/home/user/codex_ligand/output/phase2_pockets"
TOOL="${1:-all}"

echo '=== Phase 2 TG 2.1: Pocket Proposal ==='
echo

# --- fpocket ---
if [[ "$TOOL" == "all" || "$TOOL" == "fpocket" ]]; then
  echo "--- Running fpocket ---"
  if ! command -v fpocket &>/dev/null; then
    echo "WARNING: fpocket not found in PATH. Skipping."
  else
    echo "  State: 3GT8_raw"
    mkdir -p "/home/user/codex_ligand/output/phase2_pockets/3GT8_raw"
    cp "/home/user/codex_ligand/input/PPI/phase1/receptor_3GT8_raw.pdb" "/home/user/codex_ligand/output/phase2_pockets/3GT8_raw/receptor_3GT8_raw.pdb"
    cd "/home/user/codex_ligand/output/phase2_pockets/3GT8_raw"
    fpocket -f "receptor_3GT8_raw.pdb"
    cd "$OUTPUT_BASE"
    echo "    Done: 3GT8_raw"
    echo "  State: EGFR_160-185"
    mkdir -p "/home/user/codex_ligand/output/phase2_pockets/EGFR_160-185"
    cp "/home/user/codex_ligand/input/PPI/phase1/receptor_EGFR_160-185.pdb" "/home/user/codex_ligand/output/phase2_pockets/EGFR_160-185/receptor_EGFR_160-185.pdb"
    cd "/home/user/codex_ligand/output/phase2_pockets/EGFR_160-185"
    fpocket -f "receptor_EGFR_160-185.pdb"
    cd "$OUTPUT_BASE"
    echo "    Done: EGFR_160-185"
    echo "  State: EGFR_170-200"
    mkdir -p "/home/user/codex_ligand/output/phase2_pockets/EGFR_170-200"
    cp "/home/user/codex_ligand/input/PPI/phase1/receptor_EGFR_170-200.pdb" "/home/user/codex_ligand/output/phase2_pockets/EGFR_170-200/receptor_EGFR_170-200.pdb"
    cd "/home/user/codex_ligand/output/phase2_pockets/EGFR_170-200"
    fpocket -f "receptor_EGFR_170-200.pdb"
    cd "$OUTPUT_BASE"
    echo "    Done: EGFR_170-200"
  fi
  echo
fi

# --- P2Rank ---
if [[ "$TOOL" == "all" || "$TOOL" == "p2rank" ]]; then
  echo "--- Running P2Rank ---"
  if ! command -v prank &>/dev/null; then
    echo "WARNING: prank (P2Rank) not found in PATH. Skipping."
  else
    echo "  State: 3GT8_raw"
    mkdir -p "/home/user/codex_ligand/output/phase2_pockets/3GT8_raw"
    prank predict -f "/home/user/codex_ligand/input/PPI/phase1/receptor_3GT8_raw.pdb" -o "/home/user/codex_ligand/output/phase2_pockets/3GT8_raw/p2rank_output"
    echo "    Done: 3GT8_raw"
    echo "  State: EGFR_160-185"
    mkdir -p "/home/user/codex_ligand/output/phase2_pockets/EGFR_160-185"
    prank predict -f "/home/user/codex_ligand/input/PPI/phase1/receptor_EGFR_160-185.pdb" -o "/home/user/codex_ligand/output/phase2_pockets/EGFR_160-185/p2rank_output"
    echo "    Done: EGFR_160-185"
    echo "  State: EGFR_170-200"
    mkdir -p "/home/user/codex_ligand/output/phase2_pockets/EGFR_170-200"
    prank predict -f "/home/user/codex_ligand/input/PPI/phase1/receptor_EGFR_170-200.pdb" -o "/home/user/codex_ligand/output/phase2_pockets/EGFR_170-200/p2rank_output"
    echo "    Done: EGFR_170-200"
  fi
  echo
fi

echo "=== Pocket proposal complete ==="
echo "Run parser: python -m egfr_pipeline.phase2.pocket_proposal --parse"