#!/usr/bin/env python3
"""Fragment range sensitivity pilot — config, PBS, and comparison (AC-3.3).

Generates:
  1. Three config YAML files for pilot PPI docking with different fragment ranges
  2. A PBS script to run all three pilots
  3. Comparison logic to compute hotspot Jaccard similarity across ranges

Fragment ranges:
  A: 945-1006 (N-terminal +10)
  B: 955-1006 (current)
  C: 955-1015 (C-terminal +9)

Pilot specification:
  - 1 state (3GT8_raw) × 1 seed × 2,000 models
  - Comparison after completion: hotspot Jaccard > 0.7 → robust

Usage:
    python scripts/pilot_fragment_range.py --generate    # Generate configs + PBS
    python scripts/pilot_fragment_range.py --compare     # Compare pilot results

EC-3.2: All 3 Jaccard < 0.3 → "Fragment 범위 선택이 결과에 결정적 영향" WARNING.
"""

import argparse
import csv
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set, Tuple

PROJECT_ROOT = Path(__file__).resolve().parent.parent

# ---------------------------------------------------------------------------
# Fragment range definitions
# ---------------------------------------------------------------------------

FRAGMENT_RANGES = {
    "A": {"label": "N-terminal +10", "start": 945, "end": 1006},
    "B": {"label": "Current",        "start": 955, "end": 1006},
    "C": {"label": "C-terminal +9",  "start": 955, "end": 1015},
}

PILOT_STATE = "3GT8_raw"
PILOT_SEED = 0
PILOT_N_MODELS = 2000

# ---------------------------------------------------------------------------
# Config generation
# ---------------------------------------------------------------------------

_CONFIG_TEMPLATE = """\
# Pilot fragment range sensitivity — Range {range_id}: {label} ({start}-{end})
# Auto-generated by scripts/pilot_fragment_range.py
#
# Run: qsub -v RANGE={range_id} config/run_pilot_fragment.pbs

project_name: pilot_fragment_{range_id}
output_root: ./output/pilot_fragment_{range_id}

receptors:
- chain: A
  id: {state}
  pdb: input/receptors/{state}.pdb
  source_type: raw_3GT8

ppi:
  pyrosetta_result_dirs: {{}}
  pilot_fragment:
    range_id: "{range_id}"
    label: "{label}"
    residue_start: {start}
    residue_end: {end}
    partner_chain: B
    n_models: {n_models}
    seed: {seed}
    state: {state}

resources:
  scheduler: pbs
  ppi:
    cpu_per_job: 16
"""


def generate_pilot_configs(output_dir: Path) -> List[Path]:
    """Generate 3 pilot config YAML files."""
    output_dir.mkdir(parents=True, exist_ok=True)
    paths = []

    for range_id, info in FRAGMENT_RANGES.items():
        config_path = output_dir / f"pilot_fragment_{range_id}.yaml"
        content = _CONFIG_TEMPLATE.format(
            range_id=range_id,
            label=info["label"],
            start=info["start"],
            end=info["end"],
            state=PILOT_STATE,
            n_models=PILOT_N_MODELS,
            seed=PILOT_SEED,
        )
        config_path.write_text(content, encoding="utf-8")
        paths.append(config_path)
        print(f"  Config: {config_path}")

    return paths


_PBS_TEMPLATE = """\
#!/bin/bash
#PBS -q workq
#PBS -N pilot_frag_${{RANGE}}
#PBS -l nodes=node05:ppn=16
#PBS -l walltime=06:00:00
#PBS -V
#PBS -o ${{PBS_O_WORKDIR}}/pilot_frag_${{RANGE}}.o
#PBS -e ${{PBS_O_WORKDIR}}/pilot_frag_${{RANGE}}.e

# ============================================================
# Pilot Fragment Range Sensitivity (AC-3.3)
#
# Usage:
#   qsub -v RANGE=A config/run_pilot_fragment.pbs
#   qsub -v RANGE=B config/run_pilot_fragment.pbs
#   qsub -v RANGE=C config/run_pilot_fragment.pbs
# ============================================================

set -eo pipefail

cd "$PBS_O_WORKDIR"
source ~/.bashrc
conda activate pyrosetta

RANGE="${{RANGE:?RANGE is required (A, B, or C)}}"

echo "=== Pilot Fragment Range $RANGE ==="
echo "Config: config/pilot_fragment_${{RANGE}}.yaml"
echo "State: {state}, Seed: {seed}, Models: {n_models}"

python run_production.py \\
  --config "config/pilot_fragment_${{RANGE}}.yaml" \\
  --lane ppi \\
  --state {state} \\
  --seed {seed} \\
  --allocated-cpus "${{PBS_NP:-16}}"
"""


def generate_pbs_script(output_dir: Path) -> Path:
    """Generate PBS script for pilot execution."""
    output_dir.mkdir(parents=True, exist_ok=True)
    pbs_path = output_dir / "run_pilot_fragment.pbs"
    content = _PBS_TEMPLATE.format(
        state=PILOT_STATE,
        seed=PILOT_SEED,
        n_models=PILOT_N_MODELS,
    )
    pbs_path.write_text(content, encoding="utf-8")
    print(f"  PBS script: {pbs_path}")
    return pbs_path


# ---------------------------------------------------------------------------
# Hotspot comparison (post-pilot)
# ---------------------------------------------------------------------------

def load_hotspot_set(csv_path: Path) -> Set[str]:
    """Load hotspot residue IDs from ppi_hotspot_residues.csv."""
    if not csv_path.exists():
        return set()
    hotspots = set()
    with open(csv_path, encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row.get("is_hotspot", "").lower() in ("true", "1"):
                hotspots.add(row.get("residue_id", ""))
    return hotspots


def jaccard_similarity(set_a: Set[str], set_b: Set[str]) -> float:
    """Compute Jaccard similarity between two sets."""
    if not set_a and not set_b:
        return 1.0
    union = len(set_a | set_b)
    if union == 0:
        return 1.0
    return len(set_a & set_b) / union


def compare_pilot_results(
    pilot_base: Path,
    output_path: Optional[Path] = None,
) -> Tuple[List[dict], List[str]]:
    """Compare hotspot sets across 3 pilot fragment ranges.

    Args:
        pilot_base: Base directory containing pilot_fragment_A/, B/, C/

    Returns:
        (comparison_rows, warnings)
    """
    hotspot_sets: Dict[str, Set[str]] = {}

    for range_id in FRAGMENT_RANGES:
        hotspot_path = (
            pilot_base / f"pilot_fragment_{range_id}" / "workflow_b"
            / "phase1_ppi_analysis" / PILOT_STATE / "ppi_hotspot_residues.csv"
        )
        hotspot_sets[range_id] = load_hotspot_set(hotspot_path)

    # Pairwise Jaccard
    range_ids = sorted(FRAGMENT_RANGES.keys())
    comparison_rows: List[dict] = []
    warnings: List[str] = []

    for i, ra in enumerate(range_ids):
        for rb in range_ids[i + 1:]:
            j = jaccard_similarity(hotspot_sets[ra], hotspot_sets[rb])
            shared = hotspot_sets[ra] & hotspot_sets[rb]
            only_a = hotspot_sets[ra] - hotspot_sets[rb]
            only_b = hotspot_sets[rb] - hotspot_sets[ra]

            comparison_rows.append({
                "range_a": ra,
                "range_b": rb,
                "range_a_desc": f"{FRAGMENT_RANGES[ra]['start']}-{FRAGMENT_RANGES[ra]['end']}",
                "range_b_desc": f"{FRAGMENT_RANGES[rb]['start']}-{FRAGMENT_RANGES[rb]['end']}",
                "n_hotspot_a": len(hotspot_sets[ra]),
                "n_hotspot_b": len(hotspot_sets[rb]),
                "n_shared": len(shared),
                "jaccard": round(j, 4),
                "shared_residues": ";".join(sorted(shared)),
                "only_a_residues": ";".join(sorted(only_a)),
                "only_b_residues": ";".join(sorted(only_b)),
            })

            # Interpretation
            if j >= 0.7:
                interpretation = f"{ra} vs {rb}: Jaccard={j:.2f} ≥ 0.7 → robust"
            elif j >= 0.5:
                interpretation = f"{ra} vs {rb}: Jaccard={j:.2f} 0.5-0.7 → partial impact"
            else:
                interpretation = f"{ra} vs {rb}: Jaccard={j:.2f} < 0.5 → range re-selection needed"
            print(f"  {interpretation}")

    # EC-3.2: all Jaccard < 0.3
    all_jaccards = [r["jaccard"] for r in comparison_rows]
    if all_jaccards and all(j < 0.3 for j in all_jaccards):
        warnings.append(
            "Fragment 범위 선택이 결과에 결정적 영향, 구조적 검토 필요 "
            "(all pairwise Jaccard < 0.3)"
        )

    # Write comparison CSV
    if output_path and comparison_rows:
        cols = list(comparison_rows[0].keys())
        output_path.parent.mkdir(parents=True, exist_ok=True)
        with open(output_path, "w", newline="", encoding="utf-8") as f:
            w = csv.DictWriter(f, fieldnames=cols)
            w.writeheader()
            w.writerows(comparison_rows)
        print(f"  Comparison: {output_path}")

    for w in warnings:
        print(f"  WARNING: {w}")

    return comparison_rows, warnings


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Fragment range sensitivity pilot (AC-3.3)"
    )
    parser.add_argument("--generate", action="store_true",
                        help="Generate pilot config YAMLs and PBS script")
    parser.add_argument("--compare", action="store_true",
                        help="Compare pilot results (run after pilot completion)")
    parser.add_argument("--pilot_base", type=Path,
                        default=PROJECT_ROOT / "output",
                        help="Base directory for pilot outputs")
    parser.add_argument("--config_dir", type=Path,
                        default=PROJECT_ROOT / "config",
                        help="Directory for generated configs")
    args = parser.parse_args()

    if args.generate:
        print("Generating pilot fragment range configs...")
        generate_pilot_configs(args.config_dir)
        generate_pbs_script(args.config_dir)
        print("\nTo run pilots:")
        for rid in FRAGMENT_RANGES:
            print(f"  qsub -v RANGE={rid} config/run_pilot_fragment.pbs")
        return 0

    if args.compare:
        print("Comparing pilot fragment range results...")
        out = args.pilot_base / "pilot_fragment_comparison.csv"
        compare_pilot_results(args.pilot_base, out)
        return 0

    parser.print_help()
    return 1


if __name__ == "__main__":
    sys.exit(main())
